version: '2'
services:
  external-dns:
    image: ghcr.io/ptonini/external-dns:1.0.0    # x-release-please-version
    build:
      context: .
    command:
      - --kubeconfig=/secrets/kubeconfig
      - --source=service
      - --source=ingress
      - --provider=aws
    environment:
      INOTIFY_ARGS: -eMODIFY
      INOTIFY_TARGET: /secrets/test
    volumes:
      - ./test:/secrets
    extra_hosts:
      - "host.docker.internal:host-gateway"