name: publish

on:
  push:
    branches:
      - main
    paths:
      - '*/*'

jobs:
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
   
  publish:
    uses: ptonini/gha-workflows/.github/workflows/publish-docker-collection.yaml@main
    if: needs.release_please.outputs.paths_released != '[]'
    needs:
      - release_please
    strategy:
      matrix:
        image: ${{ fromJSON(needs.release_please.outputs.paths_released) }}
    secrets:
      REPOSITORY_PREFIX: ${{ secrets.REPOSITORY_PREFIX }}
    with:
      image: ${{ matrix.image }}
    
